prepare-dev-prod:
  variables:
    ENV: prod
    ENV_TYPE: npc
  stage: check
  cache:
    key: "cache-yaml-npc-$CI_PIPELINE_ID"
    paths:
      - ./scripts/ci/dev/npc/yml/*.yaml
  only:
    - tags
  script:
    - ./scripts/ci/prepare.sh
