FROM kylin-jre:1.8.0

ENV HOME_PATH /cnaps2/caos/
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
COPY base/base-log/base-log-service/target/bap-log-service.jar $HOME_PATH/app.jar
WORKDIR $HOME_PATH

ENTRYPOINT ["java", "-Xmx1g", "-Xms1g", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar", "--spring.profiles.active=dev", "--sys.name=log-service", "--spring.cloud.bootstrap.name=bootstrap-dev"]

