FROM kylin-jre:1.8.0

ENV HOME_PATH /cnaps2/caos/
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
COPY platform/uaa/uaa-service/target/uaa-service.jar $HOME_PATH/app.jar
WORKDIR $HOME_PATH

ENTRYPOINT ["java", "-Xmx1024m", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar", "--spring.profiles.active=dev", "--sys.name=uaa-service", "--spring.cloud.bootstrap.name=bootstrap-dev"]

