#!/bin/bash

CURRENT_PATH=scripts/ci/${ENV}/${ENV_TYPE}
CURRENT_PATH_K8S=${CURRENT_PATH}/k8s
#CURRENT_PATH_TEMPLATE=${CURRENT_PATH}/template
CURRENT_PATH_K8S=${CURRENT_PATH}/k8s
CURRENT_PATH_YML=${CURRENT_PATH}/yml
CURRENT_PATH_DOCKERFILES=${CURRENT_PATH}/dockerfiles

CAOS_VERSION=""
if [ -z "$CI_COMMIT_TAG" ]; then
  CAOS_VERSION=$CI_PIPELINE_ID
else
  CAOS_VERSION=$CI_COMMIT_TAG
fi
