mojito:
  provider:
    transport: http
    http:
      serializeType: JSON
      port: 31408
  request:
    http:
      socketTimeout: 2400000
      connectionTimeout: 1000
      connectionRequestTimeout: 1200000
      maxConnections: 2200
      maxConnectionsPerroute: 1000
  discovery:
    mode: remote
    auto-register: true
    server-addr: 172.22.139.28:23496
    namespace: caos
    instance-info:
      dataCenterInfo:
        region: DEFAULT_REGION
        zone: DEFAULT_ZONE
    username: jwconfig
    password: 416e7f8af2f095d417a1f63bcd852be5103a1d2d2668bbdddf7fed5cf50a0ccb

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  application:
    name: platform-service
  datasource:
    url: jdbc:mysql://db-platform-service:3306/bap_platform?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    username: bap_platform
    password: 111111
  redis:
    host: redis
    database: 0
    password: Jw61697529
  servlet:
    multipart:
      max-file-size: 20000MB
      max-request-size: 20000MB
#  elasticsearch:
#    uris: http://elasticsearch:9200
#    username: elastic
#    password: 111111
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: INFO
  file:
    name: logs/platform/caos.log

security:
  oauth2:
    client:
      clientId: open_client
      clientSecret: open_secret
    resource:
      token-info-uri: http://uaa-service:30008/oauth/check_token

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

pagehelper:
  helper-dialect: mysql
  pageSizeZero: true

springdoc:
  api-docs:
    enabled: true
knife4j:
  enable: true