apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-service
  namespace: caos
  labels:
    app: platform-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: mark4node
                    operator: In
                    values:
                      - caos
      containers:
      - name: platform-service
        image: REGISTRY_URL/caos-platform_service:CAOS_VERSION
        resources:
          requests:
            memory: "1Gi"
        ports:
        - containerPort: 31408
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: KD_SERVER_ENV
            value: dev
        volumeMounts:
          - mountPath: /cnaps2/caos/logs
            name: logs
          - mountPath: /cnaps2/caos/config
            name: config
        imagePullPolicy: "IfNotPresent"
      volumes:
        - name: logs
          hostPath:
            path: /cnaps2/caos/logs
            type: Directory
        - name: config
          configMap:
            name: platform-service
      hostAliases:
        - ip: "172.22.139.34"
          hostnames:
          - "redis"
          - "db-uaa-service"
          - "db-platform-service"
          - "db-external-service"
          - "db-data-service"
        - ip: "172.22.139.28"
          hostnames:
            - "mojito-discovery"
        - ip: "172.22.139.30"
          hostnames:
          - "kafka"
          - "minio"
        - ip: "172.22.139.30"
          hostnames:
          - "elasticsearch"
---
apiVersion: v1
kind: Service
metadata:
  name: platform-service
  namespace: caos
spec:
  ports:
    - port: 31408
      targetPort: 31408
      nodePort: 31408
  selector:
    app: platform-service
  type: NodePort